import { Survey, Detection } from "@/types/survey";

export const SEED_SURVEYS: Survey[] = [
  {
    id: "SN-2026-0007",
    name: "[DEMO — SYNTHETIC DATA] Chennai Coast · Line 07 (Synthetic Nav Track)",
    date: "2026-09-18",
    platform: "SonarForge Simulated Platform",
    sonarModel: "EdgeTech 4200 (simulated)",
    frequencyKhz: 400,
    rangeM: 75.0,
    altitudeM: 8.2,
    lineLengthKm: 2.45,
    pingCount: 1680,
    geoStatus: "UNAVAILABLE",
    status: "PROCESSED",
    verifiedCount: 6,
    suppressedCount: 8,
    coverageKm2: 0.368,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates unavailable (no nav file).",
    utmZone: "UNAVAILABLE (Synthetic demo without nav file)",
    isDemoSynthetic: true,
    dataNote: "All detections, classes, confidences, and suppression decisions in this demo survey are synthetic fixtures.",
  },
  {
    id: "SN-2026-0008",
    name: "[DEMO — SYNTHETIC DATA] Chennai Coast · Line 08 (Synthetic Track)",
    date: "2026-09-18",
    platform: "SonarForge Simulated Platform",
    sonarModel: "EdgeTech 4200 (simulated)",
    frequencyKhz: 400,
    rangeM: 75.0,
    altitudeM: 8.0,
    lineLengthKm: 2.38,
    pingCount: 1620,
    geoStatus: "UNAVAILABLE",
    status: "PROCESSED",
    verifiedCount: 5,
    suppressedCount: 7,
    coverageKm2: 0.357,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates unavailable (no nav file).",
    utmZone: "UNAVAILABLE (Synthetic demo without nav file)",
    isDemoSynthetic: true,
    dataNote: "All detections, classes, confidences, and coordinates in this survey are synthetic regression fixtures.",
  },
  {
    id: "SN-2026-0011",
    name: "[DEMO — SYNTHETIC DATA] Gulf of Mannar · Mosaic (Synthetic Track)",
    date: "2026-08-04",
    platform: "SonarForge Simulated Platform",
    sonarModel: "Klein 3000 (simulated)",
    frequencyKhz: 450,
    rangeM: 50.0,
    altitudeM: 6.5,
    lineLengthKm: 1.12,
    pingCount: 890,
    geoStatus: "UNAVAILABLE",
    status: "PROCESSED",
    verifiedCount: 3,
    suppressedCount: 4,
    coverageKm2: 0.112,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates unavailable (no nav file).",
    utmZone: "UNAVAILABLE (Synthetic demo without nav file)",
    isDemoSynthetic: true,
    dataNote: "All detections, classes, confidences, and coordinates in this survey are synthetic regression fixtures.",
  },
  {
    id: "SN-DEMO-BIKE",
    name: "[DEMO — SYNTHETIC DATA] Submerged Bicycle — Regression Test",
    date: "2026-09-26",
    platform: "SonarForge Physics Simulator",
    sonarModel: "EdgeTech 4200 (simulated)",
    frequencyKhz: 600,
    rangeM: 40.0,
    altitudeM: 7.2,
    lineLengthKm: 0.85,
    pingCount: 680,
    geoStatus: "UNAVAILABLE",  // literal coords — no real nav file
    status: "PROCESSED",
    verifiedCount: 1,
    suppressedCount: 2,
    coverageKm2: 0.068,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates are fabricated for regression testing only.",
    utmZone: "UNAVAILABLE (no nav file)",
    isDemoSynthetic: true,
    dataNote: "All detections, classes, confidences, and coordinates in this survey are synthetic regression fixtures. Do not use for any real operation.",
  },
  {
    id: "SN-DEMO-NET",
    name: "[DEMO — SYNTHETIC DATA] Net Debris — Multi-Cue Acoustic Signature",
    date: "2026-09-26",
    platform: "SonarForge Physics Simulator",
    sonarModel: "EdgeTech 4200 (simulated)",
    frequencyKhz: 400,
    rangeM: 60.0,
    altitudeM: 8.0,
    lineLengthKm: 1.20,
    pingCount: 840,
    geoStatus: "UNAVAILABLE",
    status: "PROCESSED",
    verifiedCount: 1,
    suppressedCount: 1,
    coverageKm2: 0.144,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates are fabricated for regression testing only.",
    utmZone: "UNAVAILABLE (no nav file)",
    isDemoSynthetic: true,
    dataNote: "All detections, classes, confidences, and coordinates in this survey are synthetic regression fixtures.",
  },
  {
    id: "SN-DEMO-UNKNOWN",
    name: "[DEMO — SYNTHETIC DATA] Unknown Man-Made — Open-Set Anomaly",
    date: "2026-09-26",
    platform: "SonarForge Physics Simulator",
    sonarModel: "Klein 3000 (simulated)",
    frequencyKhz: 450,
    rangeM: 45.0,
    altitudeM: 6.8,
    lineLengthKm: 0.95,
    pingCount: 720,
    geoStatus: "UNAVAILABLE",
    status: "PROCESSED",
    verifiedCount: 1,
    suppressedCount: 0,
    coverageKm2: 0.085,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates are fabricated for regression testing only.",
    utmZone: "UNAVAILABLE (no nav file)",
    isDemoSynthetic: true,
    dataNote: "All detections, classes, confidences, and coordinates in this survey are synthetic regression fixtures.",
  },
  {
    id: "SN-DEMO-RIPPLE",
    name: "[DEMO — SYNTHETIC DATA] Sand Ripple Field — Seabed Suppression",
    date: "2026-09-26",
    platform: "SonarForge Physics Simulator",
    sonarModel: "EdgeTech 4200 (simulated)",
    frequencyKhz: 400,
    rangeM: 75.0,
    altitudeM: 8.5,
    lineLengthKm: 1.50,
    pingCount: 1100,
    geoStatus: "UNAVAILABLE",
    status: "PROCESSED",
    verifiedCount: 0,
    suppressedCount: 6,
    coverageKm2: 0.225,
    operator: "DEMO — SYNTHETIC DATA. Not a real survey.",
    areaLocation: "DEMO — SYNTHETIC DATA. Coordinates are fabricated for regression testing only.",
    utmZone: "UNAVAILABLE (no nav file)",
    isDemoSynthetic: true,
    dataNote: "All suppression decisions in this survey are synthetic regression fixtures.",
  },
];

// PHASE 0 NOTE: All lat/lon in DEMO_DETECTIONS below are fabricated literals.
// They are preserved ONLY for regression test rendering of demo surveys.
// They must never appear on the real map and must be labelled DEMO in all exports.
// See surveys-view.tsx and map-view.tsx for DEMO badge enforcement.

export const SEED_DETECTIONS_LINE_07: Detection[] = [
  // 6 Verified Detections (Synthetic demo fixtures — no real georeferencing)
  {
    id: "TGT-001",
    surveyId: "SN-2026-0007",
    class: "net_debris",
    confidence: 91.2,
    rawConfidence: 84.5,
    evidence: {
      cnn: 0.85,
      shc: 0.94,
      regularity: 0.82,
      motionPenalty: 0.0,
      persistence: 0.88,
    },
    heightEstimateM: 1.25,
    shadowSide: "correct",
    bbox: { pingStart: 180, pingEnd: 220, rangeStartPx: 420, rangeEndPx: 465 },
    geo: {
      lat: null,
      lon: null,
      widthM: 2.4,
      lengthM: 6.8,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007", "SN-2026-0008"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "ACCEPTED",
  },
  {
    id: "TGT-002",
    surveyId: "SN-2026-0007",
    class: "wreck",
    confidence: 94.6,
    rawConfidence: 92.0,
    evidence: {
      cnn: 0.92,
      shc: 0.96,
      regularity: 0.88,
      motionPenalty: 0.0,
      persistence: 0.90,
    },
    heightEstimateM: 3.40,
    shadowSide: "correct",
    bbox: { pingStart: 410, pingEnd: 480, rangeStartPx: 510, rangeEndPx: 580 },
    geo: {
      lat: null,
      lon: null,
      widthM: 8.5,
      lengthM: 18.2,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007", "SN-2026-0008"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "ACCEPTED",
  },
  {
    id: "TGT-003",
    surveyId: "SN-2026-0007",
    class: "pipe_cylinder",
    confidence: 86.4,
    rawConfidence: 79.5,
    evidence: {
      cnn: 0.80,
      shc: 0.89,
      regularity: 0.91,
      motionPenalty: 0.05,
      persistence: 0.50,
    },
    heightEstimateM: 0.85,
    shadowSide: "correct",
    bbox: { pingStart: 620, pingEnd: 645, rangeStartPx: 120, rangeEndPx: 175 },
    geo: {
      lat: null,
      lon: null,
      widthM: 0.9,
      lengthM: 7.2,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "PENDING",
  },
  {
    id: "TGT-004",
    surveyId: "SN-2026-0007",
    class: "other_manmade",
    confidence: 88.0,
    rawConfidence: 82.0,
    evidence: {
      cnn: 0.82,
      shc: 0.90,
      regularity: 0.86,
      motionPenalty: 0.0,
      persistence: 0.75,
    },
    heightEstimateM: 0.65,
    shadowSide: "correct",
    bbox: { pingStart: 890, pingEnd: 915, rangeStartPx: 440, rangeEndPx: 470 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.4,
      lengthM: 1.5,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007", "SN-2026-0008"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "PENDING",
  },
  {
    id: "TGT-005",
    surveyId: "SN-2026-0007",
    class: "net_debris",
    confidence: 82.5,
    rawConfidence: 78.0,
    evidence: {
      cnn: 0.78,
      shc: 0.84,
      regularity: 0.76,
      motionPenalty: 0.0,
      persistence: 0.60,
    },
    heightEstimateM: 0.95,
    shadowSide: "correct",
    bbox: { pingStart: 1120, pingEnd: 1155, rangeStartPx: 160, rangeEndPx: 195 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.8,
      lengthM: 4.5,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "PENDING",
  },
  {
    id: "TGT-006",
    surveyId: "SN-2026-0007",
    class: "unknown_manmade",
    confidence: 76.2,
    rawConfidence: 71.0,
    evidence: {
      cnn: 0.71,
      shc: 0.79,
      regularity: 0.74,
      motionPenalty: 0.10,
      persistence: 0.50,
    },
    heightEstimateM: 1.10,
    shadowSide: "correct",
    bbox: { pingStart: 1340, pingEnd: 1375, rangeStartPx: 490, rangeEndPx: 525 },
    geo: {
      lat: null,
      lon: null,
      widthM: 2.1,
      lengthM: 3.0,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "PENDING",
  },

  // 8 Suppressed Detections (Acoustic Physics Vetoes)
  {
    id: "TGT-007",
    surveyId: "SN-2026-0007",
    class: "net_debris",
    confidence: 14.5,
    rawConfidence: 87.5,
    evidence: {
      cnn: 0.88,
      shc: 0.08,
      regularity: 0.35,
      motionPenalty: 0.0,
      persistence: 0.45,
    },
    heightEstimateM: 0.04,
    shadowSide: "absent",
    bbox: { pingStart: 310, pingEnd: 345, rangeStartPx: 190, rangeEndPx: 230 },
    geo: {
      lat: null,
      lon: null,
      widthM: 3.1,
      lengthM: 4.8,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "Shadow implies height 0.04 m (flat sediment patch)",
  },
  {
    id: "TGT-008",
    surveyId: "SN-2026-0007",
    class: "pipe_cylinder",
    confidence: 9.8,
    rawConfidence: 81.0,
    evidence: {
      cnn: 0.81,
      shc: 0.40,
      regularity: 0.28,
      motionPenalty: 0.64,
      persistence: 0.30,
    },
    heightEstimateM: 0.40,
    shadowSide: "correct",
    bbox: { pingStart: 720, pingEnd: 742, rangeStartPx: 85, rangeEndPx: 135 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.1,
      lengthM: 6.2,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "64% overlap with motion mask (heave/pitch collapse)",
  },
  {
    id: "TGT-009",
    surveyId: "SN-2026-0007",
    class: "net_debris",
    confidence: 16.0,
    rawConfidence: 83.0,
    evidence: {
      cnn: 0.83,
      shc: 0.65,
      regularity: 0.18,
      motionPenalty: 0.05,
      persistence: 0.40,
    },
    heightEstimateM: 0.55,
    shadowSide: "correct",
    bbox: { pingStart: 810, pingEnd: 840, rangeStartPx: 530, rangeEndPx: 565 },
    geo: {
      lat: null,
      lon: null,
      widthM: 2.0,
      lengthM: 3.2,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "Orientation coherence matches surrounding regional sand ripples (GRI veto)",
  },
  {
    id: "TGT-010",
    surveyId: "SN-2026-0007",
    class: "unknown_manmade",
    confidence: 8.2,
    rawConfidence: 74.0,
    evidence: {
      cnn: 0.74,
      shc: 0.05,
      regularity: 0.22,
      motionPenalty: 0.0,
      persistence: 0.35,
    },
    heightEstimateM: 0.02,
    shadowSide: "absent",
    bbox: { pingStart: 950, pingEnd: 980, rangeStartPx: 140, rangeEndPx: 175 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.9,
      lengthM: 2.6,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "No acoustic shadow detected down-range (flat seafloor)",
  },
  {
    id: "TGT-011",
    surveyId: "SN-2026-0007",
    class: "pipe_cylinder",
    confidence: 11.5,
    rawConfidence: 76.5,
    evidence: {
      cnn: 0.77,
      shc: 0.35,
      regularity: 0.30,
      motionPenalty: 0.58,
      persistence: 0.30,
    },
    heightEstimateM: 0.30,
    shadowSide: "correct",
    bbox: { pingStart: 1040, pingEnd: 1065, rangeStartPx: 460, rangeEndPx: 505 },
    geo: {
      lat: null,
      lon: null,
      widthM: 0.8,
      lengthM: 5.4,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "58% overlap with motion-artifact mask",
  },
  {
    id: "TGT-012",
    surveyId: "SN-2026-0007",
    class: "net_debris",
    confidence: 12.8,
    rawConfidence: 79.0,
    evidence: {
      cnn: 0.79,
      shc: 0.12,
      regularity: 0.31,
      motionPenalty: 0.0,
      persistence: 0.35,
    },
    heightEstimateM: 0.06,
    shadowSide: "incorrect",
    bbox: { pingStart: 1210, pingEnd: 1245, rangeStartPx: 210, rangeEndPx: 250 },
    geo: {
      lat: null,
      lon: null,
      widthM: 2.2,
      lengthM: 4.1,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "Anti-causal shadow points toward nadir (acoustic depression/scour)",
  },
  {
    id: "TGT-013",
    surveyId: "SN-2026-0007",
    class: "other_manmade",
    confidence: 15.2,
    rawConfidence: 73.0,
    evidence: {
      cnn: 0.73,
      shc: 0.15,
      regularity: 0.40,
      motionPenalty: 0.0,
      persistence: 0.30,
    },
    heightEstimateM: 0.05,
    shadowSide: "absent",
    bbox: { pingStart: 1420, pingEnd: 1445, rangeStartPx: 430, rangeEndPx: 455 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.2,
      lengthM: 1.2,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "Calculated height 0.05m below minimum trap height threshold (0.2m)",
  },
  {
    id: "TGT-014",
    surveyId: "SN-2026-0007",
    class: "unknown_manmade",
    confidence: 7.5,
    rawConfidence: 70.5,
    evidence: {
      cnn: 0.71,
      shc: 0.20,
      regularity: 0.25,
      motionPenalty: 0.72,
      persistence: 0.25,
    },
    heightEstimateM: 0.25,
    shadowSide: "correct",
    bbox: { pingStart: 1550, pingEnd: 1575, rangeStartPx: 130, rangeEndPx: 165 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.5,
      lengthM: 2.2,
      r95M: null,
      status: "UNAVAILABLE",
    },
    passes: ["SN-2026-0007"],
    suppressed: true,
    suppressionReason: "72% overlap with motion mask (yaw rate collapse)",
  },
];

export const DEMO_DETECTIONS: Detection[] = [
  // ─── SN-DEMO-BIKE (Section 56 Regression Scenario) ───
  {
    id: "TGT-BIKE-001",
    surveyId: "SN-DEMO-BIKE",
    class: "unknown_manmade",
    rawClass: "other_manmade",
    confidence: 92.4,
    rawConfidence: 86.0,
    overrideOccurred: true,
    overrideLog: "Raw YOLO proposed 'other_manmade' (86.0%). Structural graph fused 3 disjoint acoustic highlights into 1 unified target. Net veto triggered. Open-set held-out object correctly routed to 'unknown_manmade'.",
    decisionReason: "Open-set anthropogenic object verified by dual circular wheel rims, interconnected tubular framework, and physically valid 1.15m acoustic shadow relief. Successfully routed to unknown_manmade.",
    mergedComponentsCount: 3,
    evidence: {
      cnn: 0.86,
      shc: 0.88,
      regularity: 0.85,
      motionPenalty: 0.0,
      persistence: 0.85,
    },
    comprehensiveEvidence: {
      cnn: 0.86,
      shadow: 0.88,
      height: 0.90,
      circular: 0.91,
      truss: 0.88,
      tubular: 0.85,
      linear: 0.20,
      mesh: 0.04,
      rope: 0.05,
      draping: 0.02,
      floatSinker: 0.00,
      wreckStructure: 0.15,
      anthropogenic: 0.94,
      anomaly: 0.86,
      motionQuality: 0.95,
      persistence: 0.85,
      naturalSeabed: 0.05,
      structuralMerge: 0.92,
    },
    classScores: {
      net_debris: 0.08,
      wreck: 0.15,
      pipe_cylinder: 0.12,
      other_manmade: 0.45,
      unknown_manmade: 0.924,
    },
    heightEstimateM: 1.15,
    shadowSide: "correct",
    bbox: { pingStart: 280, pingEnd: 360, rangeStartPx: 320, rangeEndPx: 440 },
    geo: {
      lat: null,
      lon: null,
      widthM: 1.85,
      lengthM: 0.75,
      r95M: null,
      status: "UNAVAILABLE",
    },
    widthM: 1.85,
    lengthM: 0.75,
    r95M: null,
    diverSearchBoxM: { width: 2.8, height: 2.8 },
    passes: ["SN-DEMO-BIKE"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "ACCEPTED",
  },
  {
    id: "TGT-BIKE-FRAG1",
    surveyId: "SN-DEMO-BIKE",
    class: "unknown_manmade",
    rawClass: "unknown_manmade",
    confidence: 30.0,
    rawConfidence: 72.0,
    evidence: { cnn: 0.72, shc: 0.5, regularity: 0.4, motionPenalty: 0, persistence: 0.5 },
    heightEstimateM: 0.6,
    shadowSide: "correct",
    bbox: { pingStart: 285, pingEnd: 315, rangeStartPx: 325, rangeEndPx: 365 },
    geo: { lat: null, lon: null, widthM: 0.65, lengthM: 0.65, r95M: null, status: "UNAVAILABLE" },
    passes: ["SN-DEMO-BIKE"],
    suppressed: true,
    suppressionReason: "Fused into master physical target TGT-BIKE-001 (front wheel component)",
  },
  {
    id: "TGT-BIKE-FRAG2",
    surveyId: "SN-DEMO-BIKE",
    class: "unknown_manmade",
    rawClass: "unknown_manmade",
    confidence: 32.0,
    rawConfidence: 74.0,
    evidence: { cnn: 0.74, shc: 0.5, regularity: 0.4, motionPenalty: 0, persistence: 0.5 },
    heightEstimateM: 0.6,
    shadowSide: "correct",
    bbox: { pingStart: 325, pingEnd: 355, rangeStartPx: 395, rangeEndPx: 435 },
    geo: { lat: null, lon: null, widthM: 0.65, lengthM: 0.65, r95M: null, status: "UNAVAILABLE" },
    passes: ["SN-DEMO-BIKE"],
    suppressed: true,
    suppressionReason: "Fused into master physical target TGT-BIKE-001 (rear wheel component)",
  },

  // ─── SN-DEMO-NET (Section 57 Regression Scenario) ───
  {
    id: "TGT-NET-001",
    surveyId: "SN-DEMO-NET",
    class: "net_debris",
    confidence: 93.1,
    rawConfidence: 82.0,
    decisionReason: "Net debris classification verified by high-frequency mesh texture (0.84), continuous curved rope skeleton (0.86), flexible catenary draping (0.80), and valid 1.25m acoustic shadow relief. Demonstrates structural net evidence, NOT height alone.",
    evidence: { cnn: 0.82, shc: 0.92, regularity: 0.80, motionPenalty: 0.0, persistence: 0.85 },
    comprehensiveEvidence: {
      cnn: 0.82,
      shadow: 0.92,
      height: 0.85,
      circular: 0.08,
      truss: 0.05,
      tubular: 0.10,
      linear: 0.15,
      mesh: 0.84,
      rope: 0.86,
      draping: 0.80,
      floatSinker: 0.75,
      wreckStructure: 0.10,
      anthropogenic: 0.88,
      anomaly: 0.78,
      motionQuality: 0.92,
      persistence: 0.85,
      naturalSeabed: 0.05,
      structuralMerge: 0.60,
    },
    classScores: {
      net_debris: 0.931,
      wreck: 0.20,
      pipe_cylinder: 0.10,
      other_manmade: 0.25,
      unknown_manmade: 0.65,
    },
    heightEstimateM: 1.25,
    shadowSide: "correct",
    bbox: { pingStart: 380, pingEnd: 430, rangeStartPx: 210, rangeEndPx: 275 },
    geo: { lat: null, lon: null, widthM: 3.2, lengthM: 7.5, r95M: null, status: "UNAVAILABLE" },
    widthM: 3.2,
    lengthM: 7.5,
    r95M: null,
    diverSearchBoxM: { width: 2.6, height: 2.6 },
    passes: ["SN-DEMO-NET"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "ACCEPTED",
  },
  {
    id: "TGT-NET-002",
    surveyId: "SN-DEMO-NET",
    class: "net_debris",
    confidence: 12.0,
    rawConfidence: 81.0,
    evidence: { cnn: 0.81, shc: 0.1, regularity: 0.2, motionPenalty: 0.0, persistence: 0.3 },
    heightEstimateM: 0.02,
    shadowSide: "absent",
    bbox: { pingStart: 610, pingEnd: 645, rangeStartPx: 450, rangeEndPx: 490 },
    geo: { lat: null, lon: null, widthM: 2.5, lengthM: 3.8, r95M: null, status: "UNAVAILABLE" },
    passes: ["SN-DEMO-NET"],
    suppressed: true,
    suppressionReason: "Suppressed: Net veto triggered. Zero mesh or rope structures found despite 81% raw detector score.",
  },

  // ─── SN-DEMO-UNKNOWN (Section 58 Regression Scenario) ───
  {
    id: "TGT-UNK-001",
    surveyId: "SN-DEMO-UNKNOWN",
    class: "unknown_manmade",
    confidence: 88.5,
    rawConfidence: 74.0,
    decisionReason: "Anthropogenic structure detected with strong organized geometry (0.88) and valid acoustic shadow relief (1.40m), but evidence was insufficient for any known class (net: 0.10, pipe: 0.25, wreck: 0.32). Correctly routed to Unknown Anthropogenic Structure.",
    evidence: { cnn: 0.74, shc: 0.88, regularity: 0.82, motionPenalty: 0.0, persistence: 0.70 },
    comprehensiveEvidence: {
      cnn: 0.70,
      shadow: 0.85,
      height: 0.80,
      circular: 0.25,
      truss: 0.35,
      tubular: 0.25,
      linear: 0.20,
      mesh: 0.10,
      rope: 0.10,
      draping: 0.05,
      floatSinker: 0.00,
      wreckStructure: 0.30,
      anthropogenic: 0.92,
      anomaly: 0.89,
      motionQuality: 0.95,
      persistence: 0.70,
      naturalSeabed: 0.05,
      structuralMerge: 0.50,
    },
    classScores: {
      net_debris: 0.10,
      wreck: 0.32,
      pipe_cylinder: 0.25,
      other_manmade: 0.28,
      unknown_manmade: 0.885,
    },
    heightEstimateM: 1.40,
    shadowSide: "correct",
    bbox: { pingStart: 310, pingEnd: 360, rangeStartPx: 280, rangeEndPx: 345 },
    geo: { lat: null, lon: null, widthM: 2.8, lengthM: 3.6, r95M: null, status: "UNAVAILABLE" },
    widthM: 2.8,
    lengthM: 3.6,
    r95M: null,
    diverSearchBoxM: { width: 3.0, height: 3.0 },
    passes: ["SN-DEMO-UNKNOWN"],
    suppressed: false,
    suppressionReason: null,
    operatorReview: "ACCEPTED",
  },

  // ─── SN-DEMO-RIPPLE (Section 31 Regression Scenario) ───
  ...[1, 2, 3, 4, 5, 6].map((i) => ({
    id: `TGT-RIPPLE-00${i}`,
    surveyId: "SN-DEMO-RIPPLE",
    class: "natural_suppressed" as const,
    confidence: 10.0 + i,
    rawConfidence: 82.0 + i,
    evidence: { cnn: 0.82, shc: 0.08, regularity: 0.30, motionPenalty: 0.0, persistence: 0.20 },
    heightEstimateM: 0.03,
    shadowSide: "absent" as const,
    bbox: { pingStart: 120 * i, pingEnd: 120 * i + 40, rangeStartPx: 150 + i * 30, rangeEndPx: 195 + i * 30 },
    geo: { lat: null, lon: null, widthM: 2.5, lengthM: 4.0, r95M: null, status: "UNAVAILABLE" as const },
    passes: ["SN-DEMO-RIPPLE"],
    suppressed: true,
    suppressionReason: "Suppressed because periodic texture continued seamlessly into surrounding annular seabed and no distinct raised-object shadow was identified.",
  })),
];

